//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDIWebSite.DataContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CDIWebSiteToEntitiesDB : DbContext
    {
        public CDIWebSiteToEntitiesDB()
            : base("name=CDIWebSiteToEntitiesDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cupo> Cupoes { get; set; }
        public virtual DbSet<Evento> Eventoes { get; set; }
        public virtual DbSet<Image> Images { get; set; }
        public virtual DbSet<ImageSection> ImageSections { get; set; }
        public virtual DbSet<Inscripcione> Inscripciones { get; set; }
        public virtual DbSet<Ministerio> Ministerios { get; set; }
        public virtual DbSet<NetUser> NetUsers { get; set; }
        public virtual DbSet<Persona> Personas { get; set; }
        public virtual DbSet<Tipo> Tipoes { get; set; }
        public virtual DbSet<Request> Requests { get; set; }
    }
}
