//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDIWebSite.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cupo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cupo()
        {
            this.Eventoes = new HashSet<Evento>();
        }
    
        public int IdCupo { get; set; }
        public int CantCupo { get; set; }
        public Nullable<int> Disponibles { get; set; }
        public Nullable<int> EnUso { get; set; }
        public Nullable<int> StatusOnOff { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Evento> Eventoes { get; set; }
    }
}
