//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDIWebSite.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evento
    {
        public int IdEvento { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> IdTipo { get; set; }
        public Nullable<System.DateTime> FechaEvento { get; set; }
        public string Lugar { get; set; }
        public Nullable<int> Capacidad { get; set; }
    }
}
