//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDIWebSite.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public int IdImage { get; set; }
        public Nullable<int> IdImageSection { get; set; }
        public byte[] ImgSource { get; set; }
    
        public virtual ImageSection ImageSection { get; set; }
    }
}
