//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDIWebSite.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inscripciones
    {
        public int IdInscripciones { get; set; }
        public Nullable<int> IdHermano { get; set; }
        public Nullable<int> IdEvento { get; set; }
        public Nullable<int> Activo { get; set; }
    }
}
