//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDIWebSite.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int IdRequest { get; set; }
        public string Solicitante { get; set; }
        public string Destinatario { get; set; }
        public string Comentario { get; set; }
        public string Contacto { get; set; }
        public string Email { get; set; }
        public Nullable<int> Activo { get; set; }
    }
}
